# POST http://127.0.0.1:3000/register HTTP/1.1
# content-type: application/json

# {
#    "username":"eoeefosa",
#    "password":"emmanuel",
#    "email": "eoeeofsa@gmail.com",
#    "WhatsappNumber":"081474443220"
# }

# POST http://127.0.0.1:3000/user/register HTTP/1.1
# content-type: application/json

# {
#    "name":"eoeefosa",
#    "email":"eoeefosa78@gmail.com",
#    "password":"emmanuel"
# }



# GET  http://127.0.0.1:3000/user/people HTTP/1.1
# POST http://127.0.0.1:3000/course/createCourse HTTP/1.1
# content-type: application/json

# {
#    "title":"pharmacology"
# }

#  GET  http://127.0.0.1:3000/course/courses HTTP/1.1
# DELETE  http://127.0.0.1:3000/course/deleteCourse HTTP/1.1
# content-type: application/json

# {
#    "title":"pharmacology"
# }

# POST http://127.0.0.1:3000/course/course HTTP/1.1
# content-type: application/json

# {
#    "title":"Chemical"
# }

#  POST http://127.0.0.1:3000/bquestion/question HTTP/1.1
# content-type: application/json

# #  {
# #     "question": "God called forth the birds of the air from the ______.",
# #     "options": ["Waters", "Ground", "Sky", "Trees"],
# #     "answer": "Waters",
# #     "BR": "Genesis 1:20",
# #     "level": 1
# #   }

# {
#     "question": "What was the first thing God made?",
#     "options": ["Man", "Birds", "Light", "Seas"],
#     "answer": "Light",
#     "BR": "Genesis 1:3",
#     "level": 1
# }


  # GET http://127.0.0.1:3000/bquestion/questions HTTP/1.1



DELETE  http://127.0.0.1:3000/bquestion/question HTTP/1.1
  content-type: application/json

{
 "id": "65f7c870aa0b916af3f1899e"
}

#  PUT  http://127.0.0.1:3000/bquestion/question HTTP/1.1
# content-type: application/json

#  {
#   "id": "65f7c860aa0b916af3f1899c",
#     "question": "God called forth the birds of the air from the ______.",
#     "options": ["Waters", "Ground", "Sky", "Trees"],
#     "answer": "Waters",
#     "BR": "Genesis 1:20",
#     "level": 1
#   }
